config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  	sessions: "admins/sessions"
  }
  devise_for :users
  resources :produtos
  get "areaFuncionarios" , to: "area_funcionarios#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "produtos#index", as: "home"
  get "search", to: "produtos#search" 
  get "contato", to: "paginas#contato"
  get "sobre", to: "paginas#sobre"
  get "negado", to: "paginas#acessoNegado"
  get "compra", to: "produtos#compra"

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'forgot_password', to: 'devise/passwords#new'
    get 'reset_password', to: 'devise/passwords#edit'
  end

  devise_scope :admin do
    get 'sign_in_admin', to: 'devise/sessions#new'
    get 'sign_up_admin', to: 'devise/registrations#new'
    get 'forgot_password_admin', to: 'devise/passwords#new'
    get 'reset_password_admin', to: 'devise/passwords#edit'
  end
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  def search
    @produtos =  Produto.where("nome LIKE ? or descricao LIKE ?", "%" + params[:q] + "%", "%" + params[:q] + "%")
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new

  def new
    if user_signed_in?
      redirect_to negado_path
    elsif !admin_signed_in?
      redirect_to sign_in_admin_path
    else
      @produto = Produto.new
    end
  end

  # GET /produtos/1/edit
  def edit
    if user_signed_in?
      redirect_to negado_path
    elsif !admin_signed_in?
      redirect_to sign_in_admin_path
    end
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    if user_signed_in?
      redirect_to negado_path
    elsif !admin_signed_in?
      redirect_to sign_in_admin_path
    else
      @produto.destroy
      respond_to do |format|
        format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def compra
      if !user_signed_in? and !admin_signed_in?
        redirect_to sign_in_path
      elsif admin_signed_in?
        redirect_to negado_path
      end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :preco, :estoque, :descricao)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :nome, :class => "form-control", :placeholder => "Nome" %>
  </div>

  <div class="field">
    <%= form.text_field :preco , :class => "form-control", :placeholder => "Preço"%>
  </div>

  <div class="field">
    <%= form.number_field :estoque , :class => "form-control", :placeholder => "Estoque"%>
  </div>

  <div class="field">
    <%= form.text_area :descricao , :class => "form-control", :placeholder => "Descrição"%>

  </div>

  <div class="actions">
    <%= form.submit "Criar", :class => "btn btn-lg btn-primary btn-block" %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<div class="container">
 <% @produtos.each do |produto| %>
      <div class="page-header">
        <h1><%= produto.nome %></h1>
      </div>
      <div class="well">
        <p><%= produto.descricao %></p>
      </div>
        <h2>R$ <%= produto.preco %></h2>
        <% if produto.estoque==0 %>
            <span class="label label-danger">Esgotado</span>
        <% elsif admin_signed_in? %>
        <h2>Estoque: <%= produto.estoque %> un.</td>
        <% else %>
            <button type="button" class="btn btn-lg btn-success"><%= link_to "Comprar", compra_path %></button>
        <% end %>
        <% if admin_signed_in? %>
        <br><tr>
        <td><%= link_to 'Mostrar', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Excluir', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %>
    <% end %>
    
 </div>

app/views/produtos/compra.html.erb
<h1> Boleto </h1>
<p> Boleto gerado para se pagar o produto em questão </p>
<p> Código de barras: XXXXXXXXXXXXXXXXXX </p>

app/views/produtos/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Mostrar', @produto %> |
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<% if admin_signed_in? %>
<h1>Bem-Vindo Funcionário!</h1>
<h2>Produtos</h2>
<button type="button" class="btn btn-lg btn-success"><%= link_to 'Novo Produto', new_produto_path %></button>
<% else %>
	<h2>Produtos</h2>
<% end %>
  <tbody>
    <% @produtos.each do |produto| %>
      <div class="page-header">
        <h1><%= produto.nome %></h1>
      </div>
      <div class="well">
        <p><%= produto.descricao %></p>
      </div>
        <h2>R$ <%= produto.preco %></h2>
        <% if produto.estoque==0 %>
            <span class="label label-danger">Esgotado</span>
        <% elsif admin_signed_in? %>
        <h2>Estoque: <%= produto.estoque %> un.</td>
        <% else %>
            <button type="button" class="btn btn-lg btn-success"><%= link_to "Comprar", compra_path %></button>
        <% end %>
        <% if admin_signed_in? %>
        <br><tr>
        <td><%= link_to 'Mostrar', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Excluir', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %>
    <% end %>
  </tbody>

<br>

app/views/produtos/new.html.erb
<div class= "container">
	<h1>Novo Produto</h1>

	<%= render 'form', produto: @produto %>

	<%= link_to 'Voltar', produtos_path %>
</div>

app/views/produtos/search.html.erb
<h1> Resultado da pesquisa: </h1>

<%= render partial: "produto", object: @books %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="page-header">
    <h1><%= @produto.nome %></h1>
  </div>
  <div class="well">
    <p><%= @produto.descricao %></p>
  </div>
    <h2>R$ <%= @produto.preco %></h2>
    <% if @produto.estoque==0 %>
        <span class="label label-danger">Esgotado</span>
    <% elsif admin_signed_in? %>
    <h2>Estoque: <%= @produto.estoque %> un.</td>
    <% else %>
        <button type="button" class="btn btn-lg btn-success"><%= link_to "Comprar", compra_path %></button>
    <% end %>
 </div>

<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>