config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  	sessions: "admins/sessions"
  }
  devise_for :users
  resources :produtos
  get "areaFuncionarios" , to: "area_funcionarios#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "produtos#index", as: "home"
  get "search", to: "produtos#search" 
  get "contato", to: "paginas#contato"
  get "sobre", to: "paginas#sobre"
  get "negado", to: "paginas#acessoNegado"
  get "compra", to: "produtos#compra"

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'forgot_password', to: 'devise/passwords#new'
    get 'reset_password', to: 'devise/passwords#edit'
  end

  devise_scope :admin do
    get 'sign_in_admin', to: 'devise/sessions#new'
    get 'sign_up_admin', to: 'devise/registrations#new'
    get 'forgot_password_admin', to: 'devise/passwords#new'
    get 'reset_password_admin', to: 'devise/passwords#edit'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LojaDeInstrumentos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <%= link_to "Loja X", home_path, :class => "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Home', home_path, :class => "active" %></li>   
            <% if user_signed_in? and !admin_signed_in?%>
              <li>
                <a class="nav-link disabled" tabindex="-1" aria-disabled="true"><%= current_user.email %></a>
              </li>
              <li><%= link_to 'Sair', destroy_user_session_path, method: :delete%></li>
            <% elsif !user_signed_in? and !admin_signed_in? %>
              <li><%= link_to 'Entrar', sign_in_path%></li> 
            <% elsif admin_signed_in? and !user_signed_in? %>
              <li>
                <a class="nav-link disabled" tabindex="-1" aria-disabled="true"><%= current_admin.email %></a>
              </li>
              <li><%= link_to 'Sair', destroy_user_session_path, method: :delete%></li>
            <% else %>
              <% redirect_to destroy_user_session_path method: :delete %>
              <% redirect_to destroy_admin_session_path method: :delete %>
            <% end %>
            <li><%= link_to "Sobre", sobre_path%></li>
            <li><%= link_to "Contato", contato_path%></li>
          </ul>
          <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" action= "/search">
            <div class="form-group" >
              <input name="q" type="text" placeholder="Pesquisar produto" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Pesquisar</button>
          </form>
        </div>
        </div><!--/.nav-collapse -->
        
      </div>
    </nav>


    <div class="conteudo">
      <%= yield %>
    </div>

    <footer>
      <%= link_to "Área de funcionários", areaFuncionarios_path %>
    </footer>
  </body>
</html>